name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.x"
          cache: true
          cache-dependency-path: go.mod
      - run: go test ./...
      - uses: cachix/install-nix-action@v31
      - run: nix build .#default
